### ISSUE TITLE
Now playing song and history of played songs are erased on page switch

### ISSUE THREAD

**Issue by commagray** [innereq/morkerfyr#5]
How to reproduce:
1. Go from main page to another page using navbar.
2. Go back.
3. Repeat many times.
4. Everything is broken until the page is reloaded.

Possibly related to #2.

**Comment by koloml** [comment]
Totally related to #2. Because on every `History` component display, new ReconnectableEventSource spawns, but previous one is still alive.

**Comment by koloml** [comment]
Just check the network tab in browser inspector:

![image](https://user-images.githubusercontent.com/15185230/100353743-6ce8cd80-3008-11eb-88c4-74bf56c62a47.png)

**Comment by commagray** [comment]
BTW, 404 spam is expected. EventSource is trying to reconnect until it'll find something.

We can recuse spam somehow, and/or reduce reconnecting interval. If it's necessary, of course.
